GET https://localhost:8443/user HTTP/1.1

###

GET https://localhost:8443/user/name/Pepe HTTP/1.1

###

GET https://localhost:8443/user/name/Juan HTTP/1.1

###

GET https://localhost:8443/user/name/Andres HTTP/1.1

###

GET https://localhost:8443/user/id/1 HTTP/1.1
###
GET https://localhost:8443/user/id/2 HTTP/1.1
###
GET https://localhost:8443/user/name/pedro HTTP/1.1

###

GET https://localhost:8443/user/login HTTP/1.1

###

POST https://localhost:8443/user/login HTTP/1.1
content-type: application/json

{
    "username": "Pepe",
    "userpasswd": "cWF6V3N4JDE="
}

###
POST https://localhost:8443/user/add HTTP/1.1
content-type: application/json

{
    "username": "Juan",
    "userpasswd": "1234"
}
